# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2059f9e231ba9d99c4604adc4027c6c4907507b373a9c2d47f245d5b16f24f2035cdd91c73e5d826f986ff7c0db27f2a5fe08d62b511415eb16c6e14bc3c76ef

test:
  secret_key_base: d2ad3bdeae8a64a147a5f6256bc536e19d706c8d374242b6842e9d41327e1d0d54ddf4ea123cfa29e294da80869b722fff2b495a49210115a9ee3387645fdefe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
